# -*- coding: utf-8 -*-
"""Feature3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vErGB55OkHcJRWSavZkqfjndZN8K2yaJ
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

# Load the data
data = pd.read_csv('Cancer_Data.csv')

# Step 1: Separate data by diagnosis
malignant = data[data['diagnosis'] == 'M']
benign = data[data['diagnosis'] == 'B']

# Step 2: Select features to analyze
features = ['radius_mean', 'texture_mean', 'perimeter_mean', 'area_mean']

# Step 3: Calculate Mean, Median, and Mode for each feature
analysis = {}
for feature in features:
    analysis[feature] = {
        'Malignant': {
            'Mean': malignant[feature].mean(),
            'Median': malignant[feature].median(),
            'Mode': malignant[feature].mode().iloc[0]
                if not malignant[feature].mode().empty
                else None
        },
        'Benign': {
            'Mean': benign[feature].mean(),
            'Median': benign[feature].median(),
            'Mode': benign[feature].mode().iloc[0]
                if not benign[feature].mode().empty
                else None
        }
    }

# Display the analysis results
for feature, stats in analysis.items():
    print(f"\nFeature: {feature}")
    for diagnosis, values in stats.items():
        print(f"{diagnosis} - Mean: {values['Mean']:.2f}, Median: {values['Median']:.2f}, Mode: {values['Mode']}")

# Plot the data
plt.figure(figsize=(10, 6))
sns.histplot(malignant['radius_mean'], color='red', label='Malignant', kde=True, stat="density", bins=20)
sns.histplot(benign['radius_mean'], color='blue', label='Benign', kde=True, stat="density", bins=20)
plt.title('Distribution of Radius Mean by Diagnosis Type')
plt.xlabel('Radius Mean')
plt.ylabel('Density')
plt.legend()
plt.show()
